os: osx
matrix:
  include:
    - osx_image: xcode9
    - osx_image: xcode8
    - osx_image: xcode7.3
    - osx_image: xcode6.4
install:
  - brew update
  - brew install CLIUtils/apple/libomp
script:
  - clang++ -L$(brew --prefix libomp)/lib -I$(brew --prefix libomp)/include -Werror -Xpreprocessor -fopenmp test.cpp -lomp -o testout
  - brew test --verbose libomp
  - ./testout
